version: "2.1"
services:
  live-origin:
    image: unifiedstreaming/live:latest
    ports:
      - 80:80
    environment:
      - USP_LICENSE_KEY
      - CHANNEL=test
      - LOG_LEVEL=warn
      - PUB_POINT_OPTS=--archiving=1 --archive_length=3600 --archive_segment_length=1800 --dvr_window_length=30 --restart_on_encoder_reconnect --mpd.min_buffer_time=48/25 --mpd.suggested_presentation_delay=48/25 --hls.minimum_fragment_length=48/25 --mpd.minimum_fragment_length=48/25 --mpd.segment_template=time --hls.client_manifest_version=4 --hls.fmp4
    healthcheck:
      test: kill -0 1
      interval: 2s
      timeout: 5s
      retries: 30
  ffmpeg:
    build: ffmpeg
    environment:
      - PUB_POINT_URI=http://live-origin/test/test.isml
    entrypoint: /bin/sh -c "ffmpeg -nostats -re -listen 1 -i rtmp://0.0.0.0/live -map 0 -codec:a aac -codec:v libx264 -r 25 -g 48 -fflags genpts -write_prft pts  -movflags empty_moov+separate_moof+default_base_moof -f mp4 \"$$PUB_POINT_URI/Streams(ffmpeg)\""
    ports:
      - 1935:1935
    depends_on:
      live-origin:
        condition: service_healthy
