apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.imagePullSecret.secretName }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret.secretName }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: ffmpeg
          image: "{{ .Values.ffmpeg.repository }}:{{ .Values.ffmpeg.tag }}"
          imagePullPolicy: "{{ .Values.ffmpeg.pullPolicy }}"
          ports:
          - containerPort: 80
          env:
          - name: PUB_POINT_URI
            value: "{{ .Values.ffmpeg.pub_point_uri }}"
          - name: TRACKS
            value: {{ .Values.ffmpeg.tracks | toJson | quote }}
          {{- with .Values.env }}
          {{ toYaml . | trim | indent 10 }}
          {{ end }}
        - name: origin
          image: "{{ .Values.origin.repository }}:{{ .Values.origin.tag }}"
          imagePullPolicy: "{{ .Values.origin.pullPolicy }}"
          ports:
          - containerPort: 80
          env:
          - name: CHANNEL
            value: "{{ .Values.origin.channel }}"
          - name: PUB_POINT_OPTS
            value: "{{ .Values.origin.pub_point_opts }}"
          - name: USP_LICENSE_KEY
            valueFrom:
              secretKeyRef:
                name: {{ include "chart.fullname" . }}-license-key
                key: USP_LICENSE_KEY
          {{- with .Values.env }}
{{ toYaml . | trim | indent 10 }}
          {{ end }}
          {{- with .Values.env }}
          {{ toYaml . | trim | indent 10 }}
          {{ end }}
