{{- if and .Values.ffmpegPullSecret .Values.ffmpegPullSecret.username .Values.ffmpegPullSecret.password }}
{{- $registryAuthDocument := dict -}}
{{- $_ := set $registryAuthDocument "username" .Values.ffmpegPullSecret.username }}
{{- $_ := set $registryAuthDocument "password" .Values.ffmpegPullSecret.password }}
{{- $authMessage := printf "%s:%s" $registryAuthDocument.username $registryAuthDocument.password | b64enc }}
{{- $_ := set $registryAuthDocument "auth" $authMessage }}
{{- $dockerAuthDocument := dict .Values.ffmpegPullSecret.registryURL $registryAuthDocument }}
{{- $dockerConfigJSONDocument := dict "auths" $dockerAuthDocument -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ffmpegPullSecret.secretName }}
  {{- if .Values.ffmpegPullSecret.annotations }}
  annotations: {{- toYaml .Values.ffmpegPullSecret.annotations | nindent 4 }}
  {{- end }}
  {{- if .Values.ffmpegPullSecret.labels }}
  labels: {{- toYaml .Values.ffmpegPullSecret.labels | nindent 4 }}
  {{- end }}
data:
  .dockerconfigjson: {{ $dockerConfigJSONDocument | toJson | b64enc | quote }}
type: kubernetes.io/dockerconfigjson
{{- end }}